### ISSUE TITLE
[Bug]: The part directory of adj list and property group not generate when the vertex chunk has no edge

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphAr#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

as title 

### Expected Behavior

as title

### Minimal Reproducible Example

ldbc sample

### Environment

- Operating system:
- GraphAr version:

**Comment by lixueclaire** [comment]
Since we have introduced an edge_count file in GraphAr, the number of edge chunks can be calculated by reading this file. Therefore, this issue should not be a bug currently. @acezen , could you please have a try using the latest version of C++ SDK?

**Comment by lixueclaire** [comment]
fixed by #132 & #138
