### ISSUE TITLE
[Bug]: Inconsistency of data type in GraphAr chunks and in the info yaml file

### ISSUE THREAD

**Issue by lixueclaire** [alibaba/GraphAr#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The chunk files generated by GraphAr Writer for dataset "ldbc_sample" have inconsistent data types with the information files. For example, when the property "birthday" of "person" vertices is set to be with "string" type in the Info yaml, the type of data in generated GAR chunk files is "date32/date64" since Arrow infers that it is date when reading from the original CSV.

### Expected Behavior

The writer of GraphAr SDK should validate the type of data in Arrow Table is consistent with the data type defined in corresponding VertexInfo/EdgeInfo when writing data to GAR chunk files.

### Minimal Reproducible Example

graph: ldbc sample
vertex label: person
property: birthday

### Environment

- Operating system: not relevant
- GraphAr version: gar/v1

**Comment by acezen** [comment]
resolved by pull request #136
