### ISSUE TITLE
[Doc][Improvement] Refine the documentation about the file format of GraphAr

### ISSUE THREAD

**Issue by lixueclaire** [alibaba/GraphAr#159]
**Is your feature request related to a problem? Please describe.**
Refine and improve the introduction of the [GraphAr file format](https://alibaba.github.io/GraphAr/user-guide/file-format.html) design, to make it more clear and easy to understand for beginners.

**Describe the solution you'd like**
- Clarify the definitions of vertex ids, such as original id, global id, GraphAr internal id (inside vertex type).
- Introduce the four types of adj_list (`ordered_by_source`, `ordered_by_dest`, `unordered_by_source`, `unordered_by_dest`) in more details.

**Comment by acezen** [comment]
Resolved by PR #165
