### ISSUE TITLE
[Bug]:  Loading from S3 bucket got segment fault error

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphAr#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A segfault is seen when we use the S3 filesystem of arrow. This is likely due to the s3fs instance being a static variable. 
Even arrow 12.0.0 has use a [workaround](https://github.com/apache/arrow/pull/33858) , the segfault still been seen in GraphAr.

```bash
Filters: test_graph_info_load_from_s3
===============================================================================
All tests passed (6 assertions in 1 test case)


=================================================================
==109782==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7efd830d4867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7efd8055641d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.3+0x1b741d)

Indirect leak of 488 byte(s) in 5 object(s) allocated from:
    #0 0x7efd830d4867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7efd8055641d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.3+0x1b741d)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7efd830d4867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7efd805a4795 in OPENSSL_sk_deep_copy (/lib/x86_64-linux-gnu/libcrypto.so.3+0x205795)

Indirect leak of 27 byte(s) in 2 object(s) allocated from:
    #0 0x7efd830d4867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7efd805573aa in CRYPTO_strdup (/lib/x86_64-linux-gnu/libcrypto.so.3+0x1b83aa)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7efd830d4867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7efd8055641d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.3+0x1b741d)
    #2 0x631b81101d92d7ff  (<unknown module>)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7efd830d4867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7efd80557452 in CRYPTO_strndup (/lib/x86_64-linux-gnu/libcrypto.so.3+0x1b8452)

Indirect leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x7efd830d4c18 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0x7efd80554997  (/lib/x86_64-linux-gnu/libcrypto.so.3+0x1b5997)

SUMMARY: AddressSanitizer: 723 byte(s) leaked in 12 allocation(s).
```

And this is maybe a bug of upstream https://github.com/facebookincubator/velox/issues/4562.
referent arrow issue: https://github.com/apache/arrow/issues/15054

### Expected Behavior

application exit with no error.

### Minimal Reproducible Example

- build cpp
- run `./test_info test_graph_info_load_from_s3`

### Environment

- Operating system: Ubuntu 22.04
- GraphAr version: https://github.com/alibaba/GraphAr/commit/8ff4d99efb6bb68cdad668413921cfd1910966d2

**Comment by acezen** [comment]
The is bug issue to keep track of the upstream fix

**Comment by pitrou** [comment]
We hope to have a reliable fix for this in https://github.com/apache/arrow/pull/36442
If you are able to easily reproduce the issue, could you perhaps try one of the wheels produced in https://github.com/apache/arrow/pull/36442#issuecomment-1619874702
(click on the "crossbow" icon corresponding to your configuration, then click on "summary" in the Github Actions UI, and you should see a wheel artifact)

**Comment by acezen** [comment]
> 

Thanks for the fix and notice. This is really nice for your working. We will try the commit sooner asap.
thanks for the work again.
