### ISSUE TITLE
[Feat]:   Support data type extension in graph information base on `version` attribute of Infos

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphAr#2]
**Is your feature request related to a problem? Please describe.**
The `version` attribute of infos(graph, vertex, edge) now is only a number. Actually it can contain the implicit information that the property data types support with the version. With the version growing, the supported data types could be extended. Likes:
version 1 -> support `bool`,`int32`, `int64`, `float`, `double`, `string`
version 2 -> support `bool`,`int32`, `int64`, `float`, `double`, `string`, `date32`

**Describe the solution you'd like**
- Use string instead of number as version, something like `User Agent` message of browser.
`version` example:
`gar/v1`
`gar/v2`
`gar/v3 (user_define1, user_define2)` # suppose the version 3 or higher support user define type.

- Add a `VersionMeta` class to keep record different version supported data types and do the version string parse job.
- If the yaml contains the data type that the yaml version not support, raise error to user.

**Comment by acezen** [comment]
@lixueclaire Do you have any supplement to this feature?

**Comment by lixueclaire** [comment]
Some other works may required for this feature:
- extend DataType to support user-defined types (record type name as a string)
- ensure Builder/Writer to raise error when encounter non-supported types

**Comment by acezen** [comment]
> Some other works may required for this feature:
> 
> * extend DataType to support user-defined types (record type name as a string)
> * ensure Builder/Writer to raise error when encounter non-supported types

Nice advice, it's very helpful.
