### ISSUE TITLE
[Doc][C++]: Refine documentation comments

### ISSUE THREAD

**Issue by Thespica** [alibaba/GraphAr#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In documentation comments, `@param` name is not same as real parameter name.
Here are some differences I had discovered, maybe there are others I haven't discovered :

https://github.com/alibaba/GraphAr/blob/75dfb4234c7bb1aaaf2d408a4e3e0aed92a127a6/cpp/include/gar/graph_info.h#L1086
https://github.com/alibaba/GraphAr/blob/75dfb4234c7bb1aaaf2d408a4e3e0aed92a127a6/cpp/include/gar/graph_info.h#L1260

### Expected Behavior

`@param` name is  same as real parameter name.

### Minimal Reproducible Example

https://github.com/alibaba/GraphAr/blob/75dfb4234c7bb1aaaf2d408a4e3e0aed92a127a6/cpp/include/gar/graph_info.h#L1257
https://github.com/alibaba/GraphAr/blob/75dfb4234c7bb1aaaf2d408a4e3e0aed92a127a6/cpp/include/gar/graph_info.h#L1260

### Environment

- Operating system:
- GraphAr version:

**Comment by Thespica** [comment]
We can keep this issue for a while so that we can point it out when we found any documentation comments problems.

replace `is is` by `is`
https://github.com/alibaba/GraphAr/blob/75dfb4234c7bb1aaaf2d408a4e3e0aed92a127a6/cpp/include/gar/graph_info.h#L1056

**Comment by sighingnow** [comment]
Hi @Thespica,

Thanks for raising these issues. Would you mind to submit a pull request for a quickfix?

Thanks!
