### ISSUE TITLE
[Feat][Spark][Doc] Add examples to show how to exchange data between Nebula and GraphAr

### ISSUE THREAD

**Issue by liuxiaocs7** [alibaba/GraphAr#248]
**Is your feature request related to a problem? Please describe.**

Add examples to show how to exchange data between Nebula and GraphAr PR has been created: https://github.com/alibaba/GraphAr/pull/244.
We need to add doc for it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by acezen** [comment]
close since the PR has merged

**Comment by liuxiaocs7** [comment]
Hi, @acezen, this issue is created by this comment: https://github.com/alibaba/GraphAr/pull/244#pullrequestreview-1663936971, do we still need to update this part of the documentation?
