### ISSUE TITLE
[Doc]: The args of method annotations  is inconsistent with the real args of the method

### ISSUE THREAD

**Issue by haohao0103** [alibaba/GraphAr#253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

com.alibaba.graphar.util.FileSystem.scala
def writeDataFrame(...){}
![image](https://github.com/alibaba/GraphAr/assets/30570711/90a53aef-fac1-4ac4-bafd-c9edc8d1ffca)
The args of method annotations  is inconsistent with the real args of the method,in the ide will give red

### Expected Behavior

 args in the annotation of the method are kept consistent with the true args

### Minimal Reproducible Example

/**
   * Write input dataframe to output path with certain file format.
   *
   * **@param dataframe**
   *   DataFrame to write out.
   * @param fileType
   *   output file format type, the value could be csv|parquet|orc.
   * @param outputPrefix
   *   output path prefix.
   * **@param startChunkIndex**
   *   the start index of chunk.
   */
  def writeDataFrame(
      dataFrame: DataFrame,
      fileType: String,
      outputPrefix: String,
      offsetStartChunkIndex: Option[Int],
      aggNumListOfEdgeChunk: Option[Array[Long]]
  ): Unit = {...

### Environment

- Operating system:mac 
- GraphAr version:main

**Comment by lixueclaire** [comment]
Hi, @haohao0103 . Thank you for bringing this issue to our attention. We would greatly appreciate your assistance in resolving it.
