### ISSUE TITLE
[Bug]: FileSystem is not closed

### ISSUE THREAD

**Issue by haohao0103** [alibaba/GraphAr#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

com.alibaba.graphar.util.FileSystem.scala
def writeValue(..){}
After  close output,  we do not close fs.

### Expected Behavior

def writeValue(
      value: Long,
      outputPath: String,
      hadoopConfig: Configuration
  ): Unit = {
    val path = new Path(outputPath)
    val fs = path.getFileSystem(hadoopConfig)
    val output: FSDataOutputStream = fs.create(path, true) // create or overwrite
    // consistent with c++ library, convert to little-endian
    output.writeLong(java.lang.Long.reverseBytes(value))
    output.close()
    **fs.close()**
  }

### Minimal Reproducible Example

com.alibaba.graphar.util.FileSystem.scala
def writeValue(..){}
After  close output,  we do not close fs.

### Environment

- Operating system:mac
- GraphAr version:main

**Comment by lixueclaire** [comment]
resolved by #258
