### ISSUE TITLE
[Bug]: Reference of spark and java in website is missing

### ISSUE THREAD

**Issue by Thespica** [alibaba/GraphAr#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As titile.

### Expected Behavior

displaying scaladoc and javadoc

### Minimal Reproducible Example

![image](https://github.com/alibaba/GraphAr/assets/119573640/27c2dbb5-9808-499e-b4d8-e506fd4aeffd)
![image](https://github.com/alibaba/GraphAr/assets/119573640/731eb5a0-c4c5-423b-b1ed-411d354a52c2)

### Environment

- Operating system:
- GraphAr version:

### Further Information

scala: invalid output arguments `-DoutputDirectory`. Keep original way to generate docs.

java: use whitespace rather than tab in makefile, which may leads problems.

**Comment by acezen** [comment]
refer to html generate process: https://github.com/alibaba/GraphAr/blob/c752915bb4a8842423d91481def089e873712b7d/docs/Makefile#L53-L57

seems that the process generate api-doc of c++/java/spark before SPHINXBUILD, so the _build/html directory is not existed yet in api-doc process, and failed to generate to the directory.

The better solution is make html generate process build  SPHINXBUILD  first and then build the api-doc document.
