### ISSUE TITLE
[Feat] Integrate Neo4j spark connector as input data source

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphAr#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yixinglu** [comment]
In addition, it's better to read neo4j data and generate GraphAR files by streaming, which can avoid loading all data into memory.

**Comment by lixueclaire** [comment]
solved by #107

**Comment by acezen** [comment]
> In addition, it's better to read neo4j data and generate GraphAR files by streaming, which can avoid loading all data into memory.

Good suggestions. A issue #119 has been created for this.
