### ISSUE TITLE
[Bug][C++]: Cannot read the edge property correctly 

### ISSUE THREAD

**Issue by jasinliu** [alibaba/GraphAr#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the edge yaml format in gar-test, as [here](https://github.com/GraphScope/gar-test/blob/909af376f171b319b0425b4e2e9e055aab6ca1e9/ldbc_sample/parquet/person_knows_person.edge.yml), we can not read the property.

### Expected Behavior

It should print 'creationDate' as expected.

### Minimal Reproducible Example

https://gist.github.com/jasinliu/67d9e12fa8baabba6d5234f046eeaffa
When make it,  I see no property.

### Environment

- Operating system: Ubuntu
- GraphAr version: 0.11.1

**Comment by jasinliu** [comment]
When I remove the double tab before property_groups, it works.
 Just like [this](https://github.com/TuGraph-family/tugraph-db/pull/277/commits/0f3fe767b1333382f3faa4a73469f91100a67274).

**Comment by acezen** [comment]
sorry for the out-of-dated testing yaml， you can take https://github.com/GraphScope/gar-test/tree/main/new/ldbc_sample as example. the old one is compatible for JAVA SDK. we would update the testing ASAP.
