### ISSUE TITLE
[Feat][Format] Support `nullable` key-value in property metadata

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphAr#351]
**Is your feature request related to a problem? Please describe.**
Some graph database(like `HugeGraph`) that they have a metadata of property that show the property can have null value or not. GraphAr should support the metadata.

**Describe the solution you'd like**
Add a key  call `nullable` to `Property` struct and provide related API.
like `is_primary`

**Describe alternatives you've considered**
no alternatives

**Additional context**
related discussion #343

**Comment by Thespica** [comment]
Should the new field be alternative when parsing?

If it is required, we have to change all data, and loss compatibility backwards.

**Comment by acezen** [comment]
> Should the new field be alternative when parsing?
> 
> If it is required, we have to change all data, and loss compatibility backwards.

yes, I think it can be optional in info yaml that if the property don't contain `nullable` key, it's false by default.

**Comment by acezen** [comment]
hi, @Thespica , since the C++ library has support the feature, can you help to support the `nullable` key-value for GraphAr-Spark library too.

**Comment by SemyonSinchenko** [comment]
@acezen May we wait with a little? Cause I'm making a huge refactoring of graphar-spark (#320, #361) and merging will be pain

**Comment by acezen** [comment]
> @acezen May we wait with it a little? Cause I'm making a huge refactoring of graphar-spark (#320, #361) and merging will be pain

yes, this issue can wait until the refactor merged
