### ISSUE TITLE
 Revise the application example implementation

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphAr#44]
**Is your feature request related to a problem? Please describe.**
Currently the [examples]() of GraphAr are implement like unit test and they are not intuitive for user or developer beginner to know how to use GraphAr as example.
We need to revise the implement and make them more like an example and show case.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
related to #37

**Comment by lixueclaire** [comment]
solved by #46
