### ISSUE TITLE
Improve the document about the file format introduction and use examples

### ISSUE THREAD

**Issue by lixueclaire** [alibaba/GraphAr#65]
**Is your feature request related to a problem? Please describe.**
Improve the document about the GAR file format introduction to make it more clear. Also, re-organize and improve the examples for helping the users to getting started with GraphAr.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by acezen** [comment]
here are some format describe document can be referred:
[apache arrow](https://github.com/apache/arrow/blob/master/docs/source/format/Columnar.rst)
[apache ORC](https://orc.apache.org/docs/types.html)

**Comment by lixueclaire** [comment]
solved by #69
